Restack: ignore nodes without bounding box
Sorting by position rely on the anchor of the bounding box. If the node
doesn't have a bb, the effect fails with `AttributeError: 'NoneType'
object has no attribute 'get_anchor'`.

This commit adds a new unit test that tries to restack an empty layer
and adds a filter in `restack_positional` to filter nodes without bb to
make the test pass.