Fix TypeErrors in gcodetools.py
A lack of parentheses ends up comparing a method to a float and using
square brackets in a return causes a list to be compared to a tuple.

Fixes the following errors when parsing an arc in gcodetools.py:
    TypeError: '<' not supported between instances of 'method' and 'float'
    TypeError: '>' not supported between instances of 'list' and 'tuple'