Add test for color_negative.py with a HSL color
The test fails because the color_negative.py assumes the color is RGB and tries to substract 255 from the second and third values.

Test output:

```
$ pytest tests/test_color_negative.py
================================================================================================================================= test session starts ==================================================================================================================================
platform linux -- Python 3.12.3, pytest-9.0.2, pluggy-1.6.0
rootdir: /home/x/src/extensions
configfile: tox.ini
plugins: xvfb-2.0.0, cov-3.0.0
collected 2 items

tests/test_color_negative.py .F                                                                                                                                                                                                                                                  [100%]

======================================================================================================================================= FAILURES =======================================================================================================================================
____________________________________________________________________________________________________________________________ ColorNegativeTest.test_colors _____________________________________________________________________________________________________________________________

self = <tests.test_color_negative.ColorNegativeTest testMethod=test_colors>

    def test_colors(self):
        """Run all color tests"""
        for x, (inp, outp) in enumerate(self._test_list(self.color_tests)):
            outp = inkex.Color(outp)
            if isinstance(inp, (list, tuple)):
                color = inkex.ColorRGB(inp)
            else:
                color = inkex.Color(inp)
            got = self.effect._modify_color("fill", color)
            self.assertTrue(
                isinstance(got, inkex.Color),
                "Bad output type: {}".format(type(got).__name__),
            )
            outp, got = str(outp), str(got.to(outp.name))
>           self.assertEqual(
                outp, got, "Color mismatch, test:{} {} != {}".format(x, outp, got)
            )
E           AssertionError: 'hsl(232, 50, 50)' != 'hsl(203, 100, 100)'
E           - hsl(232, 50, 50)
E           ?       -  ^   ^
E           + hsl(203, 100, 100)
E           ?      +   ^^   ^^
E            : Color mismatch, test:17 hsl(232, 50, 50) != hsl(203, 100, 100)

tests/test_inkex_extensions.py:68: AssertionError
=============================================================================================================================== short test summary info ================================================================================================================================
FAILED tests/test_color_negative.py::ColorNegativeTest::test_colors - AssertionError: 'hsl(232, 50, 50)' != 'hsl(203, 100, 100)'
============================================================================================================================= 1 failed, 1 passed in 0.38s ==============================================================================================================================

```